print ('Previous month budget')
milk = int ( input ('Milk:\t\t' ) )
sugar = int ( input ('Sugar:\t\t' ) )
tea = int ( input ('Tea:\t\t\t' ) )
biscuits = int ( input ('Biscuits:\t' ) )
print ('\nNext month budget')
print ('Milk:\t\t', int ( milk * 1.2) )
print ('Sugar:\t\t', int ( sugar * 1.2) )
print ('Tea:\t\t\t', int ( tea * 1.2) )
print ('Biscuits:\t', int ( biscuits * 1.2) )
print ('----------------------------------')
print ('Total:\t\t', int ( milk * 1.2 + sugar * 1.2 + tea * 1.2 + biscuits * 1.2 ) )