
print ('I am studying in \"FCIT\" and I am in \'first semester\'')
print ('1\n23\n456\n7891')
print ('NAME\tSEMESTER\tGPA')
print ('ALI\tSECOND\t\t3.50')
print ('AHMAD\tTHIRD\t\t3.33')
print('RIZWAN\tFOURTH\t\t3.87')
print ('SADIA\tFIFTH\t\t4.00')
print("There once was a person named 'Muhammad Eman' who lived in 'Faisalabad'. At the age of 19, 'Muhammad Eman' went to college at 'FCIT'", end='')
print("'Muhammad Eman' graduated and went to work as a 'Data Engineer'. Then, 'Muhammad Eman' adopted a(n) ANIMAL named 'Zeus.'", end='')
print("They both lived happily ever after!", end='.')
print ('*\n*\t*\n*\t*\t*\n*\t*\t*\t*\n*\t*\t*\t*\t*')
print ('          *')
print ('        * * ')
print ('       *  * ')
print ('      *   * ')
print ('     *    * ')
print ('    *     *')
print ('   *      *')
print ('  *       *')
print (' *        *')
print ('***********')
print ('*******')
print ('   *   ')
print ('   *   ')
print ('   *   ')
print ('   *   ')
print ('   *   ')
print (' ***** ')
print ('|-----------|')
print ('|    1      |')
print ('|   123     |')
print ('|  12345    |')
print ('| 1234567   |')
print ('| 123456789 |')
print ('|  1234567  |')
print ('|   12345   |')
print ('|    123    |')
print ('|     1     |')
print ('*****************')
print ('*\t\t*\n*\t\t*\n*\t\t*\n*\t\t*\n*\t\t*\n*\t\t*\n*\t\t*\n*\t\t*')
print ('*****************')
print ('         *     ')
print ('        * *    ')
print ('       *   *   ')
print ('      *     *  ')
print ('     *       * ')
print ('    ***********')
print ('   *           * ')
print ('  *             *')
print (' *               *')
print ('*                 *')
